### ISSUE TITLE
[ui error]fix &  improvement on slash menu

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#136]
![Screenshot 2024-09-23 at 8 56 52 PM](https://github.com/user-attachments/assets/846ae626-59c8-4064-b909-b3ce4c0e9b53)

- [x] reduce gap between texts and frame, there's blank space

- [x] update bg color as per new ui/bg color and same stroke as dock: 3A3A3A

Fix: the todo shows 1,2 in bubble menu
![Screenshot 2024-09-23 at 8 56 36 PM](https://github.com/user-attachments/assets/19fef2c4-d4e1-4f19-9d75-534d7e3a32be)

**Comment by immadsahin** [comment]
on select & hover of the menu use the same stroke as dock icons hover effect.

**Comment by hiteshgurnani10-thera** [comment]
I am wokring on it can you assign it to me ?
@sajdakabir

**Comment by Hitesh-gurnani** [comment]
I am working on it can you assign this to me ? @sajdakabir @oliursahin

**Comment by Hitesh-gurnani** [comment]
by move todo menu up as it is used frquently you mean task list right ? @oliursahin

**Comment by Hitesh-gurnani** [comment]
https://github.com/marchhq/march/pull/158

**Comment by immadsahin** [comment]
Ignore the order change for now
