### ISSUE TITLE
[SAT-91] [BUG] Markdown isn't working properly

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#15]
issues: 
1. upon choosing the to-do format from floating menu, it does not work.

2. the floating menu looks long, I guess we should only give a few options such as bold, italic, strike off, todo, code block for now till we get to slash menu.
3. the floating menu is opening in empty line by default.

<sub>[SAT-91](https://linear.app/marchhq/issue/SAT-91/[bug]-markdown-isnt-working-properly)</sub>

**Comment by deewakar-k** [comment]
@oliursahin im working on this!
