### ISSUE TITLE
[ui] add dark mode toggle & profile icons on dock on hover

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#169]
for now the dock is animated and has three icons : inobx, today, spaces.

on hover the dock should expand vertically/ it's height, by height to accommodate dark mode toggle icon, profile & feedback

here is the link to the figma designs where you can find expanded dock the last frame: https://www.figma.com/design/VH3rrq9pPP3TFcbXzfF7DN/copy-of-march-UI?node-id=1-519&t=XMw7pbmqo7uAu7D1-1

**Comment by oliursahin** [comment]
testing a webhook for SAT-175

**Comment by lixelamos** [comment]
Assign this to me ,I'll get to it

**Comment by immadsahin** [comment]
go ahead @lixelamos

**Comment by Deepanshudks** [comment]
can you assign this to me?

**Comment by immadsahin** [comment]
hey @Deepanshudks , its already asigned to @lixelamos please pick something else.
