### ISSUE TITLE
[ Bug]: in today page the date should be updated according to current date

### ISSUE THREAD

**Issue by sajdakabir** [emptyarrayhq/emptyarray#184]
<img width="506" alt="Screenshot 2024-10-02 at 10 40 22 AM" src="https://github.com/user-attachments/assets/442c5a59-ecc9-4c96-957a-ceecd8214796">

**Comment by Hitarthsheth07** [comment]
Heyy can I work on this issue?

**Comment by siv-io** [comment]
Hey @sajdakabir the date *is* showing current date. Can you please specify the details.

**Comment by sajdakabir** [comment]
@Hitarthsheth07, if you carefully notice the today icon showing the 24, it should be today's date..
![today](https://github.com/user-attachments/assets/9c455de1-58db-4635-91e5-dd4930567b2f)

**Comment by sajdakabir** [comment]
<img width="331" alt="Screenshot 2024-10-03 at 8 47 02 AM" src="https://github.com/user-attachments/assets/f6b18d35-f9a6-4f80-9672-e18ed797a0a3">
The icon looks different from the sidebar and it seems to be too large as well.
