### ISSUE TITLE
add privacy policy url to login page

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#204]
links:

**Comment by Hitesh-gurnani** [comment]
can you assign this to me ?
@oliursahin

**Comment by immadsahin** [comment]
@Hitesh-gurnani — url: https://www.notion.so/marchhq/Terms-Privacy-67fb3e8525c04fcfa73dca152ecc1dec?pvs=4

**Comment by Hitesh-gurnani** [comment]
By continuing, you agree to our
terms of services and our privacy policy.

We've two terms of services and privacy policy on which of these do i need to add?

**Comment by immadsahin** [comment]
add same link to both
