### ISSUE TITLE
[ui] add loading screen with a message in on-boarding last step

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#212]
after integration/stack page on boarding, on continue it takes some time to get to the workspace/ account.<br><br>we need to have a proper message for that, or just our logo blinking.

**Comment by adhirajkar3103** [comment]
Hello @oliursahin , can you assign me this task?

**Comment by immadsahin** [comment]
![loading screen(1)](https://github.com/user-attachments/assets/a4b92903-3ed9-4c82-ac21-d8496d6c8dac)

url to the figma:  https://www.figma.com/design/VH3rrq9pPP3TFcbXzfF7DN/copy-of-march-UI?node-id=151-2&m=dev&t=9rBopip8Gj9HkE3R-1

@adhirajkar3103

**Comment by adhirajkar3103** [comment]
@oliursahin what will be the callback url for github auth?

**Comment by deewakar-k** [comment]
> @oliursahin what will be the callback url for github auth?

callback for github is handled in app/auth

**Comment by adhirajkar3103** [comment]
<img width="1432" alt="Screenshot 2024-10-04 at 10 16 27 PM" src="https://github.com/user-attachments/assets/cfcf086f-6278-40f6-90db-49be351dc6c2">

Getting this error after authorising github

**Comment by immadsahin** [comment]
@adhirajkar3103 hey, do you still have a blocker on this?

**Comment by thestoneroller** [comment]
I can work on this issue
