### ISSUE TITLE
fix notes store w new backend changes

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#226]
- [ ] \~\~minor ui improvement such as replacing the stack icon with text button. see figma design for nore: \~\~[~~https://www.figma.com/design/VMVSHyLb3cofjSZwWkUZ9q/White-mode-initials?node-id=0-1&node-type=canvas&t=Y2xZWV2O587uC6ta-0~~](https://www.figma.com/design/VMVSHyLb3cofjSZwWkUZ9q/White-mode-initials?node-id=0-1&node-type=canvas&t=Y2xZWV2O587uC6ta-0)
- [ ] ~~when the notes page loads first time it shows loading in description area, instead create an untitled note when they land on notes page the pointer stays in title.~~
- [ ] ~~enable jump to description on enter from title ( now the title is expanding)~~
- [ ] ~~BUG: notes do not save immediately if i go to a different page and come back the note title is not there. I can only see description text.~~
- [ ] ~~BUG: if i go to a different page and come back to note page, each time it creates an untitled note.~~

- [ ] data are not being updated/saved in notes — apply changes as per backend
- [ ] Pointer issue in description, the pointer has to be manually placed to write
- [ ] Shift enter/ enter : does not work as they should: make enter to jump to description when on title, and in description shift+ enter to break line.

**Comment by Deepanshudks** [comment]
Can you assign this to me?
