### ISSUE TITLE
command+ S: global search

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#233]
this should be blazingly fast: on command press a command bar opens to search items, on two keywords start showing suggestions to > go to

**Comment by hanzili** [comment]
hey! Can I work on it?

**Comment by nishaaannnt** [comment]
@oliursahin are we talking about something like this?

<img width="698" alt="Screenshot 2024-10-24 at 10 05 40 PM" src="https://github.com/user-attachments/assets/94bed087-26c1-4575-b72a-179f0da272f4">

we can use - https://react-cmdk.com/

**Comment by nishaaannnt** [comment]
> @oliursahin are we talking about something like this?
> 
> <img alt="Screenshot 2024-10-24 at 10 05 40 PM" width="698" src="https://private-user-images.githubusercontent.com/100792085/379860250-94bed087-26c1-4575-b72a-179f0da272f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTg0MDAsIm5iZiI6MTcyOTg1ODEwMCwicGF0aCI6Ii8xMDA3OTIwODUvMzc5ODYwMjUwLTk0YmVkMDg3LTI2YzEtNDU3NS1iNzJhLTE3OWYwZGEyNzJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODRlNzFlZDViMzEwOTlkMmFmY2Q4M2QwNTcwOTA3MDViYmZmZTNiNjdiYWE4MGZhNjUwMmYzZDdiZDk3NDllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GSiygP3MVKcXqVpv0ov1UUXGeu6xvu6sNjQKmKQsVB0">
> we can use - https://react-cmdk.com/

would love to work on this, if this is what we are thinking of. or you can let me know about the requirements

**Comment by immadsahin** [comment]
@nishaaannnt yes you can use react-cmdk and we have specific design in figma for the modal.

**Comment by nishaaannnt** [comment]
@oliursahin we need to work on moving the item first right? is there any issue open or it?

**Comment by immadsahin** [comment]
yes, schedule the item first — here is the issue : [https://github.com/marchhq/march/issues/409](https://github.com/marchhq/march/issues/409)

**Comment by immadsahin** [comment]
link to the figma modal design: [https://www.figma.com/file/VH3rrq9pPP3TFcbXzfF7DN/Page%201?node-id=0-1](https://www.figma.com/file/VH3rrq9pPP3TFcbXzfF7DN/Page%201?node-id=0-1)
