### ISSUE TITLE
Command +C: contextual create

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#234]
example: if pressed on inbox create an item in inbox from the input text<br><br>if pressed on this week: show list with input text for status.<br><br>if i type something on this week for example 'x'

list shows like this:<br><br>add 'x' in todo.  shortcut 1<br>add 'x' in in progress : 2<br><br>similar for other properties such as labels<br><br>in reading list<br><br>add link in 'lebel name' shortcut: 1<br>add link in ' lebel name'     2

**Comment by C-W-D-Harshit** [comment]
Can you assign it to me?

**Comment by immadsahin** [comment]
@C-W-D-Harshit let me know if you need more context on this

**Comment by immadsahin** [comment]
@C-W-D-Harshit this will be unassigned automatically by eod as per the community rule, wandering if there's any draft pr?

**Comment by eniiku** [comment]
hi @oliursahin. can i pick this up?
