### ISSUE TITLE
polish reading list ui

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#258]
- [ ]  responsive from 13 inch mac to 16.

<img src="https://uploads.linear.app/f6339ea4-5a30-452a-b653-19536d377dff/92133eb5-879f-4190-875b-f3e8a2275a1d/969a5f4e-1420-4523-84bd-48d4d54419ff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MzM5ZWE0LTVhMzAtNDUyYS1iNjUzLTE5NTM2ZDM3N2RmZi85MjEzM2ViNS04NzlmLTQxOTAtODc1Yi1mM2U4YTIyNzVhMWQvOTY5YTVmNGUtMTQyMC00NTIzLTg0YmQtNDhkNGQ1NDQxOWZmIiwiaWF0IjoxNzI4NDExMjg3LCJleHAiOjMzMjk4OTcxMjg3fQ.dzz66I1Ptoyh_YuBqhQ13SLhugmsvuhq3gV2Yljree4 " alt="Screenshot 2024-10-08 at 11.34.34 PM.png" width="1433" height="732" />

this is how it looks on a 13 inch mac, gap needs to be reduced by a bit in the left left and up.

- [ ]  if there is no favicon it shows as favicon text which looks ugly

<img src="https://uploads.linear.app/f6339ea4-5a30-452a-b653-19536d377dff/fde1efcd-2b54-47e2-9956-cd9b60dbdac2/aa099c58-9ad4-4a27-977d-b80f366ef75d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MzM5ZWE0LTVhMzAtNDUyYS1iNjUzLTE5NTM2ZDM3N2RmZi9mZGUxZWZjZC0yYjU0LTQ3ZTItOTk1Ni1jZDliNjBkYmRhYzIvYWEwOTljNTgtOWFkNC00YTI3LTk3N2QtYjgwZjM2NmVmNzVkIiwiaWF0IjoxNzI4NDExMjg3LCJleHAiOjMzMjk4OTcxMjg3fQ.bNcKScQNB42r4aWNSAebO1MX7KlooQMMRrWkyo7opHk " alt="Screenshot 2024-10-08 at 11.31.36 PM.png" width="707" height="206" />

- [ ]  show the url just below title as per figma.
- [ ] the url icon can be removed and the title is itself a clickable url.
- [ ] the input bar is scrolling along with the items in case of many items ( i guess that's because of responsiveness)
- [ ]  remove the outlier color, adjust the input bar as per figma, it looks little bigger on a 13 inch mac.

**Comment by hanzili** [comment]
Im currently adding the filter by label feature on this page. I can work on this after i finish that one!

**Comment by immadsahin** [comment]
@hanzili please wait for the inbox pr to be merged before working on this

**Comment by immadsahin** [comment]
this is cleared to be worked on @hanzili
