### ISSUE TITLE
[ui] dueDate prop in expanded views

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#284]
In other places, such as inbox items we have an icon to set due date of an item.

when an item is in expanded view and has a due date: show the date and make it changeable

when the item do not have due date present show the icon that we are using in inbox hover item— to set due date.

on the following pages it needs to be implemented:

1. Inbox
2. Today
3. Week
4. current spaces

**Comment by TanmayAdithya** [comment]
I can work on this issue and combine the changes in this PR #317
