### ISSUE TITLE
fix Inbox menu ui & description

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#311]
- [X] transparent bg on menu making it ugly when opened on items.

![Screenshot 2024-10-16 at 12.10.17 AM.png](https://uploads.linear.app/f6339ea4-5a30-452a-b653-19536d377dff/65fff93f-763c-4fb6-a48b-3deb32d818fb/c6a6dfe3-ff87-4da5-8395-78dc33aaa436?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MzM5ZWE0LTVhMzAtNDUyYS1iNjUzLTE5NTM2ZDM3N2RmZi82NWZmZjkzZi03NjNjLTRmYjYtYTQ4Yi0zZGViMzJkODE4ZmIvYzZhNmRmZTMtZmY4Ny00ZGE1LTgzOTUtNzhkYzMzYWFhNDM2IiwiaWF0IjoxNzI5MDE5NDMxLCJleHAiOjMzMjk5NTc5NDMxfQ.TnCcM4yxosL8z0ZIBLOzjI5tgxIbYbKDaRQLnt_lL0Q "=447x")

- [ ] the entire description is showing under title, restrict to one sentence and dots..

![Screenshot 2024-10-16 at 12.15.59 AM.png](https://uploads.linear.app/f6339ea4-5a30-452a-b653-19536d377dff/92f496f6-f1b4-4641-9739-a777125a0ee2/34425a9b-56fe-40dd-8978-fb0cd274541f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MzM5ZWE0LTVhMzAtNDUyYS1iNjUzLTE5NTM2ZDM3N2RmZi85MmY0OTZmNi1mMWI0LTQ2NDEtOTczOS1hNzc3MTI1YTBlZTIvMzQ0MjVhOWItNTZmZS00MGRkLTg5NzgtZmIwY2QyNzQ1NDFmIiwiaWF0IjoxNzI5MDE5NDQ3LCJleHAiOjMzMjk5NTc5NDQ3fQ.wO-ZPSs-JmtgD859upwpwudC14ijgs6nxPos0WRto2c "=927x")

**Comment by thestoneroller** [comment]
@oliursahin I can work on this. (I fixed it as well, I can open the PR)

**Comment by deewakar-k** [comment]
> @oliursahin I can work on this. (I fixed it as well, I can open the PR)

it is fixed in #313

**Comment by thestoneroller** [comment]
> > @oliursahin I can work on this. (I fixed it as well, I can open the PR)
> 
> it is fixed in #313

I see. Fast like the flash.

**Comment by deewakar-k** [comment]
> @oliursahin I can work on this. (I fixed it as well, I can open the PR)

you can work on the description.

**Comment by thestoneroller** [comment]
> > @oliursahin I can work on this. (I fixed it as well, I can open the PR)
> 
> you can work on the description.

Yeah it's done. Although for the background, instead of changing the shadcn's code, I added `bg-background` class to ContextMenuContent

![image](https://github.com/user-attachments/assets/7d700ba0-ac0a-429c-a31c-6e0eb80d979a)

![image](https://github.com/user-attachments/assets/8f21f8a6-ece9-472a-b11f-1ec4fdd827c2)

**Comment by deewakar-k** [comment]
@TanmayAdithya can you share img for the link description as mentioned by @oliursahin above, because that was not looking pretty. and i changed shadcn file because it will be reusable instead of mentioning bg-background everytime we need a context menu

**Comment by thestoneroller** [comment]
> @TanmayAdithya can you share img for the link description as mentioned by @oliursahin above, because that was not looking pretty. and i changed shadcn file because it will be reusable instead of mentioning bg-background everytime we need a context menu

Image as in the code implementation?
