### ISSUE TITLE
Improve connect your stack ui in onboarding

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#321]
use the same list ui — we have used in profile to maintain same everywhere.

**Comment by Hitesh-gurnani** [comment]
Can you assign this to me @oliursahin ?

**Comment by nishaaannnt** [comment]
@oliursahin hello, i would like to work on this. we have to follow the figma file for this right?

**Comment by sajdakabir** [comment]
@nishaaannnt its all yours

**Comment by nishaaannnt** [comment]
@sajdakabir hey wanted to clarify few things - 

1. we are focusing only on the UI currently ? or do we need to also work with logic
2. the ui is similar to the profile section stack and so is the logic, why not just call the component over the onboarding stack as well? it will also work with the logic. 
3. the stack page will only be visible after login, so the user prop can be passed in it, if i am right. 

kindly let me know of the above

**Comment by sajdakabir** [comment]
@nishaaannnt 
1. we are focusing on both UI and functionality
2. yes, please use the same component.
3. yes you are right

**Comment by nishaaannnt** [comment]
@sajdakabir let me know your review about this - 
On 90% - 
<img width="1280" alt="Screenshot 2024-10-22 at 10 37 58 PM" src="https://github.com/user-attachments/assets/3fc9919f-8a91-43da-9d41-5d3ba885e684">

on 100 % -
<img width="1280" alt="Screenshot 2024-10-22 at 10 38 26 PM" src="https://github.com/user-attachments/assets/af3b4933-5529-431e-b250-9c8057eee06f">

on 100% scroll in enabled, so content is visible.

also 
1. had to wrap the layout with authprovider
2. necessary context was required to be imported in the page.

**Comment by immadsahin** [comment]
@nishaaannnt 
— don't use any border/hover color as the call to action is 'connect"
— no need to show the title 'Integration", connect your stack already says what it is.

**Comment by nishaaannnt** [comment]
> @nishaaannnt — don't use any border/hover color as the call to action is 'connect" — no need to show the title 'Integration", connect your stack already says what it is.

1. sure this will be done
2. as i am using a component, if i remove it from here, it will also not be visible in profile sections.  react with a thumbs up if that will work, or let know if you have anything else

**Comment by immadsahin** [comment]
@nishaaannnt in that case we need add a message separately in profile page— instead here is a better idea:

— we can replace integrations text with 'connect your stack" so having the same text in profile section will work.

additionally, we can remove the stack button here, to make the page more clean.

**Comment by immadsahin** [comment]
removing the current giant title and stack icon will free up space, I guess the page will look good with the changes suggested—  show us once.

**Comment by nishaaannnt** [comment]
> @nishaaannnt in that case we need add a message separately in profile page— instead here is a better idea:
> 
> — we can replace integrations text with 'connect your stack" so having the same text in profile section will work.
> 
> additionally, we can remove the stack button here, to make the page more clean.

stack button means the stack logo right? 
and about the text, that's a great idea indeed. will try and put a screenshot here

**Comment by nishaaannnt** [comment]
> removing the current giant title and stack icon will free up space, I guess the page will look good with the changes suggested— show us once.

here is how it looks - 

<img width="1280" alt="Screenshot 2024-10-22 at 11 29 41 PM" src="https://github.com/user-attachments/assets/a616c528-3cd8-42b4-b0b5-dc743967403d">
<img width="1280" alt="Screenshot 2024-10-22 at 11 29 55 PM" src="https://github.com/user-attachments/assets/f84bb1ff-5772-4772-9f29-787151a025be">
