### ISSUE TITLE
schedule an item modal

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#409]

**Comment by nishaaannnt** [comment]
@oliursahin we are talking about this right?
there is a modal for calendar as well as move item.

1. schedule item
<img width="671" alt="Screenshot 2024-11-02 at 10 34 32 AM" src="https://github.com/user-attachments/assets/bbf89cb8-7f33-493f-a0fb-63924f8ebe27">

2. move item
<img width="596" alt="Screenshot 2024-11-02 at 10 36 04 AM" src="https://github.com/user-attachments/assets/d3ff28c6-cef1-4a8d-a0dc-411ee8f6b7b4">

and they open after clicking these icons (which do not do anything)-
<img width="164" alt="Screenshot 2024-11-02 at 10 35 09 AM" src="https://github.com/user-attachments/assets/f1ee67a5-404f-4de0-86dc-26f82179d8db">

so what i can do is, **start with move item first**, which seems easy right now - 

1. create modal file in components -> move item modal
2. assuming there is an api to get all the march folders of a user
3. and an api to add the item to new file

i will check this today, got some work side by side, so will try my best. Let me know anything if i am missing anything
