### ISSUE TITLE
Contextual move

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#538]
The move icon can be used to move item anywhere whether in a space or inside an item using a contextual modal will help achieving that if the modal is opened in inbox it wont show inbox as suggestion to move.<br><br>here is how it's gonna be: 

Search placeholder text " specify the target item: todo, note, event etc" <br><br>suggested spaces:<br>move to notes<br>move to reading list

**Comment by madhav-relish** [comment]
@oliursahin Do you have design in mind for this?

**Comment by immadsahin** [comment]
@madhav-relish  yeah, sharing with you on discord.
