### ISSUE TITLE
[feat] raycast extention

### ISSUE THREAD

**Issue by sajdakabir** [emptyarrayhq/emptyarray#58]
docs: https://developers.raycast.com/

ref extension: https://github.com/raycast/extensions/blob/6df4425b42c5b9e4266fa08f26a3d85ad4f64ea3/extensions/bmrks/README.md

**Comment by piyushmishra1416** [comment]
Hi @sajdakabir can I work on this issue?

**Comment by sajdakabir** [comment]
sure

**Comment by oliursahin** [comment]
Initial version:
1. Create Item in Inbox and today selection
2. search items and go to

**Comment by immadsahin** [comment]
If i have the extension here is what I would like to do with that:

1. set up an alias /shortcut to join the now 'happening meeting' : option+j
2. search agenda: to check meetings of the day or its description todo — on click goes to description of the meet in march ( in case i need to add any meeting) : option+a
3. search global item by name and and go to: 
4. create an item in inbox with an alias or shortcut: option +shift+i
5. create an item in today: option+shift+t
6. create an item in this week: option+shift+w


@piyushmishra1416

**Comment by piyushmishra1416** [comment]
Sure working on it.

**Comment by piyushmishra1416** [comment]
Task Completed:

- Created a  command to add an item.
- Created a command to view all the items.
- Added google OAuth setup.

Moving Forward:

- Investigating how to handle authentication flow further, specifically how to create and manage access tokens after OAuth authentication.
- Working on integrating database functionality to save items created via the extension.
