### ISSUE TITLE
feedback: go to link is not provided in github pulls

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#584]
<img src="https://uploads.linear.app/f6339ea4-5a30-452a-b653-19536d377dff/3d793f5c-7ae4-4baa-a7a8-18a74cd51df5/ab4069d7-824c-4bd1-b21d-411e8e94d8cf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MzM5ZWE0LTVhMzAtNDUyYS1iNjUzLTE5NTM2ZDM3N2RmZi8zZDc5M2Y1Yy03YWU0LTRiYWEtYTdhOC0xOGE3NGNkNTFkZjUvYWI0MDY5ZDctODI0Yy00YmQxLWIyMWQtNDExZThlOTRkOGNmIiwiaWF0IjoxNzMxNTYyNTg1LCJleHAiOjMzMzAyMTIyNTg1fQ.BovLepVT3isj58UjeEkJkg2Hai51Jsx1Ji_8-Z_wqHk " alt="Screenshot 2024-11-14 at 11.03.49 AM.png" width="1179" height="194" />

This pull is added in my march inbox as I was added as a reviewer, but there is no link embedded with the icon or somewhere to go to github directly

**Comment by tanbirali** [comment]
Hey, can I get this done, 
As I was surfing through the codebase, I found the icon embedding with a url can be done here https://github.com/marchhq/march/blob/713f7b1b5eeb57191974edba134687a1601d85bd/apps/frontend/src/components/atoms/ItemList.tsx#L26-L49
All that needs to be done is pass the source url and wrap the icon with the link to that url
