### ISSUE TITLE
feedback: connect calendar link is not provided in meetings space

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#588]
<img src="https://uploads.linear.app/f6339ea4-5a30-452a-b653-19536d377dff/61d87b8c-e095-4ac1-873a-6d4d0b99a3ff/bc6c181c-b9de-4e65-84a4-bbfffa7549ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MzM5ZWE0LTVhMzAtNDUyYS1iNjUzLTE5NTM2ZDM3N2RmZi82MWQ4N2I4Yy1lMDk1LTRhYzEtODczYS02ZDRkMGI5OWEzZmYvYmM2YzE4MWMtYjlkZS00ZTY1LTg0YTQtYmJmZmZhNzU0OWFjIiwiaWF0IjoxNzMxNTg2MzE5LCJleHAiOjMzMzAyMTQ2MzE5fQ.N772LOSwz1s8LPqER3vO4qKnRbcquGYOP5h_URi89G4 " alt="Screenshot 2024-11-14 at 11.13.06 AM.png" width="691" height="349" />

if the calendar is not connected, let the calendar text underlined white font to indicate that thats a link to to perform action

**Comment by tanbirali** [comment]
Can I take this, as I can see all that needs to be done here is to wrap the `calender` text in a `span` and give it the required styling 
https://github.com/marchhq/march/blob/cd5d6b8e039935d5fa74c3dca1e9750a1d0dca50/apps/frontend/src/components/meetings/InitialMeet.tsx#L74-L76
