### ISSUE TITLE
[feat] file-assets and profile pic support

### ISSUE THREAD

**Issue by sajdakabir** [emptyarrayhq/emptyarray#60]

**Comment by hrshkshri** [comment]
Hi @sajdakabir, Would appreciate a detailed description of this issue... Having a little hard time understanding the issue here.

**Comment by sajdakabir** [comment]
hey @hrshkshri ,
You need to write an API that allows users to add images to item/issue descriptions and also upload their profile pictures. The images should be stored in AWS S3, with the following folder structure:

* For item attachments: <user_uuid>/item/<item_uuid>/item_attachment
* For profile pictures: user/<user_uuid>/

If you have any other queries join our [discord](https://discord.gg/sugJGckV86)

**Comment by hrshkshri** [comment]
> hey @hrshkshri , You need to write an API that allows users to add images to item/issue descriptions and also upload their profile pictures. The images should be stored in AWS S3, with the following folder structure:
> 
> * For item attachments: <user_uuid>/item/<item_uuid>/item_attachment
> * For profile pictures: user/<user_uuid>/
> 
> If you have any other queries join our [discord](https://discord.gg/sugJGckV86)

Hmmm, I see.
So for upload are we using Multer??

**Comment by sajdakabir** [comment]
yes
